### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by o-starling** [starling94/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by starling94** [comment]
Зробимо блок про перелік навиків та хоббі.

**Comment by o-starling** [comment]
Hard skills:
- HTML/CSS;
- Basic knowledge of JS;
- SAP Business Technology Platform

Soft skills
- readiness to learn and acquire new knowledge and skills in a short time;
- stress resistance and ability to work with short deadlines;
- high level of time management when working in a team and independently;
- attention to detail.

Hobbies:
- traveling;
- taking photos and videos during the vacations and posting them on my Instagram account;
- eating cherries in my parent's garden
